### PR TITLE
Force HTTPS #53

### PR DESCRIPTION
**Pull request by dqwiki**
Fix for #53

### CODE REVIEW

**Comment by TParis** [comment]
These 9 lines should be implemented as a function in unblocklib.php and called with 1 line.

**Comment by dqwiki** [comment]
:checkered_flag:

**Comment by TParis** [comment]
There needs to be a exit() on unblocklib.php at line 40 to prevent disabling for header redirection by the user's browser.
http://php.net/manual/en/function.exit.php

**Comment by dqwiki** [comment]
I don't follow.

**Comment by TParis** [comment]
Done

**Comment by dqwiki** [comment]
+1

**Pull request merged**
