### PR TITLE
Fix: Too much text issue #75

### PR DESCRIPTION
**Pull request by dqwiki**
Pull request for #75

### CODE REVIEW

**Comment by TParis** [comment]
What happens if you type into one of these fields and then press <enter> instead of clicking submit?

Also, why are you using var name = ""; when you could just pass the actual name of the object in the function.  Or, better yet, pass "this".

**Comment by dqwiki** [comment]
The blank initialization I thought was required for JS, but that could just be porting from my Java days.

And does $this work in JS code in some way? cause it's a JS set of code, not PHP.

Otherwise working.

**Comment by dqwiki** [comment]
This should address concerns in one way or another.

**Comment by TParis** [comment]
Converted to jQuery, please perform code review.

**Comment by dqwiki** [comment]
Besides figuring out the cosmetics, the code seems solid, but i'm no js expert, so I can only certify by testing.

That said, thoughts about the White background on the blue overall background? Maybe some different colors?

**Comment by dqwiki** [comment]
Front Page could use some cosmetics work, but functionality is there.
+1

**Pull request merged**
